In [2]:
import torch
from torchmetrics.functional import accuracy, precision, recall, confusion_matrix

# 两组数据长度相等

In [3]:
preds1 = torch.tensor(
    [
        [0.75, 0.05, 0.05, 0.05, 0.05],  # 1
        [0.05, 0.75, 0.05, 0.05, 0.05],  # 1
        [0.05, 0.05, 0.75, 0.05, 0.05],  # 0
        [0.05, 0.05, 0.05, 0.75, 0.05],  # 0
    ]
)
target1 = torch.tensor([0, 1, 3, 2])

In [4]:
preds2 = torch.tensor(
    [
        [0.05, 0.50, 0.05, 0.05, 0.05],  # 1
        [0.05, 0.05, 0.05, 0.05, 0.75],  # 1
        [0.05, 0.05, 0.75, 0.05, 0.05],  # 1
        [0.05, 0.05, 0.05, 0.05, 0.75],  # 0
    ]
)
target2 = torch.tensor([1, 4, 2, 3])

In [5]:
preds12 = torch.cat((preds1, preds2), dim=0)
targets12 = torch.cat((target1, target2), dim=0)
preds12

tensor([[0.7500, 0.0500, 0.0500, 0.0500, 0.0500],
        [0.0500, 0.7500, 0.0500, 0.0500, 0.0500],
        [0.0500, 0.0500, 0.7500, 0.0500, 0.0500],
        [0.0500, 0.0500, 0.0500, 0.7500, 0.0500],
        [0.0500, 0.5000, 0.0500, 0.0500, 0.0500],
        [0.0500, 0.0500, 0.0500, 0.0500, 0.7500],
        [0.0500, 0.0500, 0.7500, 0.0500, 0.0500],
        [0.0500, 0.0500, 0.0500, 0.0500, 0.7500]])

In [6]:
_, preds12_ = preds12.max(dim=-1)
preds12_

tensor([0, 1, 2, 3, 1, 4, 2, 4])

## accuracy

In [7]:
accuracy(preds=preds1, target=target1, task="multiclass", num_classes=5, top_k=1)

tensor(0.5000)

In [8]:
accuracy(preds=preds2, target=target2, task="multiclass", num_classes=5, top_k=1)

tensor(0.7500)

In [9]:
# 这里可以看到,只有两组数据相等的情况下才能计算准确率的平均值
accuracy(preds=preds12, target=targets12, task="multiclass", num_classes=5, top_k=1)

tensor(0.6250)

In [10]:
accuracy(preds=preds12_, target=targets12, task="multiclass", num_classes=5, top_k=1)

tensor(0.6250)

In [11]:
# 两组数据取平均值是可以的
(0.5 + 0.75) / 2

0.625

## precision 不能取平均

In [12]:
precision(preds=preds1, target=target1, task="multiclass", num_classes=5, average=None)

tensor([1., 1., 0., 0., 0.])

In [13]:
precision(preds=preds2, target=target2, task="multiclass", num_classes=5, average=None)

tensor([0.0000, 1.0000, 1.0000, 0.0000, 0.5000])

In [14]:
precision(
    preds=preds12, target=targets12, task="multiclass", num_classes=5, average=None
)

tensor([1.0000, 1.0000, 0.5000, 0.0000, 0.5000])

In [15]:
precision(
    preds=preds12_, target=targets12, task="multiclass", num_classes=5, average=None
)

tensor([1.0000, 1.0000, 0.5000, 0.0000, 0.5000])

## recall 不能取平均

In [16]:
recall(preds=preds1, target=target1, task="multiclass", num_classes=5, average=None)

tensor([1., 1., 0., 0., 0.])

In [17]:
recall(preds=preds2, target=target2, task="multiclass", num_classes=5, average=None)

tensor([0., 1., 1., 0., 1.])

In [18]:
recall(preds=preds12, target=targets12, task="multiclass", num_classes=5, average=None)

tensor([1.0000, 1.0000, 0.5000, 0.0000, 1.0000])

In [19]:
recall(preds=preds12_, target=targets12, task="multiclass", num_classes=5, average=None)

tensor([1.0000, 1.0000, 0.5000, 0.0000, 1.0000])

## confusion_matrix 不能取平均

In [38]:
# normalize="none" 代表按照不归一化
# normalize="true" 代表按照ture的一行的和为1
# normalize="pred" 代表按照pred的一列的和为1
# normalize="all"  代表按照全部和为1
confusion_matrix(
    preds=preds1, target=target1, task="multiclass", num_classes=5, normalize="true"
)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [39]:
confusion_matrix(
    preds=preds2, target=target2, task="multiclass", num_classes=5, normalize="true"
)

tensor([[0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])

In [40]:
confusion_matrix(
    preds=preds12, target=targets12, task="multiclass", num_classes=5, normalize="true"
)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.0000, 0.5000],
        [0.0000, 0.0000, 0.0000, 0.0000, 1.0000]])

In [41]:
confusion_matrix(
    preds=preds12_, target=targets12, task="multiclass", num_classes=5, normalize="true"
)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.0000, 0.5000],
        [0.0000, 0.0000, 0.0000, 0.0000, 1.0000]])

### normalize="true" example

In [ ]:
# normalize="true"
cm = torch.tensor(
    [
        [
            0.0000,
            0.0385,
            0.1923,
            0.0769,
            0.3462,
            0.0000,
            0.2692,
            0.0000,
            0.0000,
            0.0769,
        ],
        [
            0.0000,
            0.1500,
            0.2000,
            0.0500,
            0.4500,
            0.0000,
            0.0000,
            0.0500,
            0.0500,
            0.0500,
        ],
        [
            0.0000,
            0.1667,
            0.2500,
            0.2083,
            0.2917,
            0.0000,
            0.0833,
            0.0000,
            0.0000,
            0.0000,
        ],
        [
            0.0435,
            0.0435,
            0.1739,
            0.3478,
            0.1739,
            0.0000,
            0.0000,
            0.1304,
            0.0435,
            0.0435,
        ],
        [
            0.0000,
            0.0000,
            0.5000,
            0.2500,
            0.1000,
            0.0000,
            0.0500,
            0.0500,
            0.0000,
            0.0500,
        ],
        [
            0.0000,
            0.0769,
            0.2692,
            0.2308,
            0.1538,
            0.0000,
            0.0000,
            0.0385,
            0.1538,
            0.0769,
        ],
        [
            0.0345,
            0.0000,
            0.4483,
            0.2759,
            0.1034,
            0.0000,
            0.0345,
            0.0345,
            0.0345,
            0.0345,
        ],
        [
            0.0417,
            0.1250,
            0.2500,
            0.0833,
            0.1667,
            0.0000,
            0.0833,
            0.1250,
            0.0417,
            0.0833,
        ],
        [
            0.0000,
            0.0294,
            0.1176,
            0.0588,
            0.5588,
            0.0000,
            0.1765,
            0.0294,
            0.0000,
            0.0294,
        ],
        [
            0.0000,
            0.2333,
            0.3000,
            0.0667,
            0.3000,
            0.0000,
            0.0333,
            0.0000,
            0.0333,
            0.0333,
        ],
    ]
)

In [ ]:
cm.sum(dim=-1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9999, 1.0001, 1.0000, 0.9999,
        0.9999])

In [ ]:
cm[0].sum()

tensor(1.)

In [ ]:
cm[:, 0].sum()

tensor(0.1197)

# 两组数据长度不相等

In [24]:
preds2_ = torch.cat(
    (
        preds2,
        torch.tensor([[0.05, 0.05, 0.05, 0.75, 0.05], [0.05, 0.05, 0.75, 0.05, 0.05]]),
    ),
    dim=0,
)
target2_ = torch.cat((target2, torch.tensor([3, 1])), dim=0)

## accuracy

In [25]:
# 两组数据不相等情况下的得分不能取平均值
accuracy(preds=preds2_, target=target2_, task="multiclass", num_classes=5, top_k=1)

tensor(0.6667)

In [26]:
(0.5 + 0.75) / 2

0.625

In [27]:
preds2_.shape

torch.Size([6, 5])