In [18]:
import torch

In [19]:
q = torch.tensor(
    [
        [1.0, 1.0, 1.0],
    ]
)
q

tensor([[1., 1., 1.]])

In [25]:
# 实际情况应该不会发生这样的情况?
k = v = torch.tensor(
    [
        [1.0, 1.0, 1],  # q应该和这一行的相似度
        [99.0, 99.0, 99.0],  # 但实际上和这一行相似度更大
    ]
)
k

tensor([[ 1.,  1.,  1.],
        [99., 99., 99.]])

In [26]:
attn = q @ k.T
attn

tensor([[  3., 297.]])

In [27]:
attn = attn.softmax(dim=-1)
attn
# 表示和k的第一行没有相似度,和k的第二行相似度很高,与实际情况很不同

tensor([[0., 1.]])

In [28]:
v

tensor([[ 1.,  1.,  1.],
        [99., 99., 99.]])

In [29]:
attn @ v
# 完全忽略的v的第一行的结果

tensor([[99., 99., 99.]])